#!/bin/sh
input="$(amixer get Master)"
volstat="$(echo "$input" | grep "\[on\]" | awk '{print $3}')"
limit="$(echo "$input" | grep "Limits:" | awk '{print $5}')"

volume="$((( ( $volstat * 100 + $limit / 2 ) / $limit )))"

if [ "$volume" -gt "70" ]; then
        icon="🔊"
elif [ "$volume" -lt "30" ]; then
        icon="🔈"
else
        icon="🔉"
fi

#convert volume from log scale to lin scale

printf "%s %s%s\n" "$icon" "$volume" "%"
