#!/bin/bash
VBoxManage startvm ubuntu_server --type headless &&
sleep 35

IP=`VBoxManage guestproperty enumerate ubuntu_server | grep IP | grep -o -w -P -e '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' | grep 192`

ssh server@$IP
